import fs from 'node:fs'
//  typescript转js配置（采用swc包转）
const config = JSON.parse(fs.readFileSync(`${process.cwd()}/.swcrc`, 'utf-8'))

// 引入一份ts类型，对标typescript开发体验
/** @type {import('jest').Config} */
const jestConfig = {
  // 转译配置
  transform: {
    // 为 Solid.js 的 TSX 文件使用特定的 Babel 配置
    'solid/.*\\.tsx?$': ['babel-jest'],
    // 其他文件保持现有的 SWC 配置。Includes `.mjs` / `.cjs` so ESM-only
    // dependencies (e.g. @lingui/core 6.x and its message-utils helper)
    // get re-emitted as CJS once they're whitelisted from
    // transformIgnorePatterns below.
    '^(?!solid/).*\\.(tsx?|jsx?|mjs|cjs)$': ['@swc/jest', { ...config }],
  },
  extensionsToTreatAsEsm: ['.ts', '.tsx'],
  /**
   * 运行每个测试文件之前-执行这个路径里面的内容。
   * 这里用来配置@testing-library/jest-dom，
   * 并加载其api-typescript类型补充
   */
  setupFilesAfterEnv: ['<rootDir>/rules/setup-jest.ts'],
  /**
   * 单测里面，如需要使用到dom，这里需设置为jsdom
   */
  testEnvironment: 'jsdom',

  /**
   * Skip generated `@types` directories — composite projects emit `.d.ts`
   * + transpiled `.jsx` there, and jest would re-run those duplicates.
   * Also skip Playwright e2e specs (`solid/excel/e2e/`) — those run under
   * `npm run e2e` from `solid/excel/`, not jest.
   */
  testPathIgnorePatterns: ['/node_modules/', '/@types/', '/solid/excel/e2e/'],

  /**
   * - wasm-pkg/: ships its own package.json from wasm-pack; haste-map
   *   would otherwise flag duplicates. Regenerated by `npm run build:wasm`.
   * - .claude/: contains agent worktrees during multi-agent development;
   *   each holds a full repo copy that haste-map would dupe-detect.
   */
  modulePathIgnorePatterns: ['<rootDir>/solid/excel/wasm-pkg/', '<rootDir>/.claude/'],

  /**
   * 模块名称映射，用于解析 @einfach/core 和 @einfach/react 包
   */
  moduleNameMapper: {
    '^@einfach/core$': '<rootDir>/vanilla/core/src',
    '^@einfach/spreadsheet-ui-core$': '<rootDir>/vanilla/spreadsheet-ui-core/src',
    '^@einfach/utils$': '<rootDir>/vanilla/utils/src',
    '^@einfach/react$': '<rootDir>/react/react/src',
    '^@einfach/react-utils$': '<rootDir>/react/utils/src',
    '^@einfach/react-form$': '<rootDir>/react/form/src',
    '^@einfach/solid$': '<rootDir>/solid/solid/src',
    '^@einfach/solid-form$': '<rootDir>/solid/form/src',
    // CSS / asset imports become an inert object during jest runs so test
    // files that touch a component which `import './foo.css'` still load
    // without a parse error. Solid dialogs co-locate their styles next to
    // the .tsx; without this stub jest would try to parse the .css as JS.
    '\\.(css|less|sass|scss)$': '<rootDir>/rules/css-stub.cjs',
  },

  /**
   * `@lingui/core` (6.x) ships ESM-only (`"type": "module"`,
   * `exports: { ".": "./dist/index.mjs" }`) and pulls in
   * `@lingui/message-utils` + `@messageformat/*` the same way. Jest's
   * default behavior is to skip transforming `node_modules`, which
   * leaves the `import` syntax in place and trips the runtime CommonJS
   * parser. Whitelist the entire chain so SWC transforms them.
   *
   * pnpm hoists into `node_modules/.pnpm/<pkg>@<ver>/node_modules/<pkg>`,
   * so the negative lookahead must match the pnpm-flat path too.
   */
  transformIgnorePatterns: [
    '/node_modules/(?!(\\.pnpm/)?(@lingui|@messageformat)[+/])',
  ],
}
export default jestConfig
