import type { ApiPackage } from './types'

export const coreTypeSections: ApiPackage['sections'] = [
  {
    title: '核心类型契约',
    navLabel: '核心类型',
    description: '这些类型描述 atom、store、异步值和可组合工具的输入输出。',
    entries: [
      {
        name: 'Atom',
        role: '只读 atom',
        description: '任意可读取状态的基础接口。',
        code: 'const labelAtom: Atom<string> = atom((get) => get(nameAtom))',
        kind: 'type',
      },
      {
        name: 'WritableAtom',
        role: '可写 atom',
        description: '带 write 函数的 atom 接口。',
        code: 'const setNameAtom: WritableAtom<null, [string], void> = atom(null, write)',
        kind: 'type',
      },
      {
        name: 'AtomEntity',
        role: '源 atom',
        description: '以值或更新函数写入的源 atom 类型。',
        code: 'const countAtom: AtomEntity<number> = atom(0)',
        kind: 'type',
      },
      {
        name: 'Read',
        role: '读取函数',
        description: 'atom 的 read 函数类型。',
        code: 'const read: Read<string> = (get) => get(nameAtom)',
        kind: 'type',
      },
      {
        name: 'Write',
        role: '写入函数',
        description: 'atom 的 write 函数类型，可读取和写入任意 atom。',
        code: 'const write: Write<[string], void> = (get, set, name) => set(nameAtom, name)',
        kind: 'type',
      },
      {
        name: 'Getter',
        role: '读取器',
        description: '在 read、write 或框架外逻辑中读取 atom。',
        code: 'const readName = (get: Getter) => get(nameAtom)',
        kind: 'type',
      },
      {
        name: 'Setter',
        role: '写入器',
        description: '在 write 或框架外逻辑中写入 WritableAtom。',
        code: "const rename = (set: Setter) => set(nameAtom, 'Ada')",
        kind: 'type',
      },
      {
        name: 'ReadOptions',
        role: '读取选项',
        description: 'read 函数收到的 abort 与 getter/setter 能力。',
        code: "const read: Read<string> = (_get, options: ReadOptions) => 'ready'",
        kind: 'type',
      },
      {
        name: 'Store',
        role: 'Store 契约',
        description: '包含 getter、setter、sub 与 clear 的状态容器接口。',
        code: 'const store: Store = createStore()',
        kind: 'type',
      },
      {
        name: 'AtomState',
        role: '状态推导',
        description: '从 Atom 类型取出它承载的状态类型。',
        code: 'type Name = AtomState<typeof nameAtom>',
        kind: 'type',
      },
      {
        name: 'AtomAsyncState',
        role: '异步状态推导',
        description: '从 Promise atom 类型取出 resolve 后的值类型。',
        code: 'type User = AtomAsyncState<typeof userAtom>',
        kind: 'type',
      },
      {
        name: 'AtomSetParameters',
        role: '写入参数推导',
        description: '从 WritableAtom 推导 setter 需要的参数元组。',
        code: 'type Params = AtomSetParameters<typeof saveAtom>',
        kind: 'type',
      },
      {
        name: 'AtomSetResult',
        role: '写入结果推导',
        description: '从 WritableAtom 推导 setter 的返回值类型。',
        code: 'type Result = AtomSetResult<typeof saveAtom>',
        kind: 'type',
      },
      {
        name: 'PromiseStatus',
        role: 'Promise 状态',
        description: '增强 Promise 的 pending、fulfilled、rejected 状态联合。',
        code: "const status: PromiseStatus = 'pending'",
        kind: 'type',
      },
      {
        name: 'StatesWithPromise',
        role: '增强 Promise',
        description: '带 status、value、reason 的 Promise 接口。',
        code: 'const pending: StatesWithPromise<User> = store.getter(userAtom)',
        kind: 'type',
      },
      {
        name: 'ContinuablePromise',
        role: '可继续 Promise',
        description: '可在状态变化后继续获取结果的 Promise 契约。',
        code: 'const task: ContinuablePromise<User> = pending',
        kind: 'type',
      },
    ],
  },
  {
    title: '历史类型契约',
    navLabel: '历史类型',
    description: 'createHistory 使用这些类型描述事务、回放器与可选持久化端口。',
    entries: [
      {
        name: 'History',
        role: '历史实例',
        description: '撤销、重做、事务与原子回放器的接口。',
        code: 'const history: History = createHistory(store)',
        kind: 'type',
      },
      {
        name: 'HistoryDirection',
        role: '回放方向',
        description: 'undo 或 redo 的方向联合。',
        code: "const direction: HistoryDirection = 'undo'",
        kind: 'type',
      },
      {
        name: 'HistoryOp',
        role: '历史操作',
        description: '一条可回放的 before/after 变更。',
        code: "const op: HistoryOp = { key: 'title', before: 'A', after: 'B' }",
        kind: 'type',
      },
      {
        name: 'HistoryEntry',
        role: '历史事务',
        description: '带 id、可选标签和一组操作的已提交事务。',
        code: "const entry: HistoryEntry = { txId: 'tx-1', ops: [] }",
        kind: 'type',
      },
      {
        name: 'HistoryStackState',
        role: '历史栈',
        description: '包含 entries 和 cursor 的只读栈状态。',
        code: 'const state: HistoryStackState = history.getState()',
        kind: 'type',
      },
      {
        name: 'HistoryApplier',
        role: '回放函数',
        description: '注册 key 对应的 undo/redo 写回逻辑。',
        code: 'const apply: HistoryApplier = (_get, set, op) => { set(titleAtom, op.after as string) }',
        kind: 'type',
      },
      {
        name: 'HistoryPersistPort',
        role: '持久化端口',
        description: '为历史 append、裁剪、游标和恢复提供异步端口。',
        code: 'const persist: HistoryPersistPort = { /* 实现 append / load 等方法 */ }',
        kind: 'type',
      },
      {
        name: 'CreateHistoryOptions',
        role: '历史选项',
        description: '配置 cap、persist、txId 生成与错误上报。',
        code: 'const options: CreateHistoryOptions = { cap: 100 }',
        kind: 'type',
      },
    ],
  },
  {
    title: '动态缓存类型契约',
    navLabel: '缓存类型',
    description: '为参数化 atom 工厂声明缓存、键和调试标签。',
    entries: [
      {
        name: 'CreateCacheStomOptions',
        role: '缓存选项',
        description: 'createCacheStom 的 atom 工厂、键函数、调试名与容量配置。',
        code: "const options: CreateCacheStomOptions<[string], Atom<string>> = {\n  createAtom: (id) => atom(id), debuggerKey: 'item'\n}",
        kind: 'type',
      },
    ],
  },
]
