import type { ApiPackage } from './types'

export const reactFormApiPackage: ApiPackage = {
  id: 'react-form',
  label: 'React Form',
  packageName: '@einfach/react-form',
  summary: '基于 atom 的 React 表单实例、字段订阅与规则校验。',
  sections: [
    {
      title: '表单与字段',
      navLabel: '表单字段',
      description: '表单值保存在独立 atom 中，字段只订阅自己的路径切片。',
      entries: [
        {
          name: 'useForm',
          role: '表单实例',
          description: '创建 FormInstance，可配置 initialValues、受控 values 与值变更回调。',
          code: "const form = useForm({ initialValues: { email: '' } })",
        },
        {
          name: 'FormProps',
          role: '表单选项',
          description: 'useForm 的 initialValues、values、onValuesChange 等属性类型。',
          code: "const props: FormProps<{ email: string }> = { initialValues: { email: '' } }",
          kind: 'type',
        },
        {
          name: 'Form',
          role: '表单 Context',
          description: '通过 Context 向子字段提供 FormInstance。',
          code: '<Form formInstance={form}><ProfileFields /></Form>',
        },
        {
          name: 'FormContext',
          role: '表单 Context',
          description: 'React 表单实例 Context；通常由 Form 间接使用。',
          code: 'const form = useContext(FormContext)',
        },
        {
          name: 'useField',
          role: '字段读写',
          description: '读取字段值并返回 onChange 写入函数。',
          code: "const { value, onChange } = useField<string>('email', { formInstance: form })",
        },
        {
          name: 'UseFieldOption',
          role: '字段选项',
          description: 'useField 的可选 formInstance。',
          code: 'const options: UseFieldOption = { formInstance: form }',
          kind: 'type',
        },
        {
          name: 'useFieldValue',
          role: '字段订阅',
          description: '订阅指定字段路径的当前值。',
          code: "const email = useFieldValue<string>('email', { formInstance: form })",
        },
        {
          name: 'UseFieldValueOption',
          role: '读取选项',
          description: 'useFieldValue 的可选 formInstance。',
          code: 'const options: UseFieldValueOption = { formInstance: form }',
          kind: 'type',
        },
        {
          name: 'useSetField',
          role: '字段写入',
          description: '取得写入指定字段路径的回调。',
          code: "const setEmail = useSetField<string>('email', { formInstance: form })\nsetEmail('ada@example.com')",
        },
        {
          name: 'UseSetFieldOption',
          role: '写入选项',
          description: 'useSetField 的可选 formInstance。',
          code: 'const options: UseSetFieldOption = { formInstance: form }',
          kind: 'type',
        },
        {
          name: 'useFormValues',
          role: '表单值订阅',
          description: '订阅 FormInstance 的完整 values atom。',
          code: 'const values = useFormValues(form)',
        },
        {
          name: 'FormItem',
          role: '字段 UI',
          description: '接收一个 React 元素，为它注入 value、onChange 和校验事件。',
          code: '<FormItem name="email" rules={[{ required: true }]}><TextInput /></FormItem>',
        },
        {
          name: 'FormItemFc',
          role: '字段 UI 实现',
          description: 'FormItem 的未 memo 化函数组件。',
          code: 'const Item = FormItemFc',
        },
        {
          name: 'FormItemProps',
          role: '字段 UI 属性',
          description: 'FormItem 的 name、rules、label 与子元素属性类型。',
          code: "const props: FormItemProps<typeof TextInput> = { name: 'email', children: <TextInput /> }",
          kind: 'type',
        },
      ],
    },
    {
      title: '校验',
      navLabel: '校验',
      description: '规则与字段路径绑定；验证方法在字段事件或显式调用时执行。',
      entries: [
        {
          name: 'useValidator',
          role: '字段校验',
          description: '注册字段规则，并返回 message 与按触发事件分组的方法。',
          code: "const { message, methods } = useValidator('email', { rules: [{ required: true }] })\nawait methods.onChange?.()",
        },
        {
          name: 'UseRulesOption',
          role: '校验选项',
          description: 'useValidator 的 formInstance、rules、label 类型。',
          code: 'const options: UseRulesOption = { rules: [{ required: true }] }',
          kind: 'type',
        },
        {
          name: 'validatorItem',
          role: '单条校验',
          description: '按规则校验一个值，供自定义校验流程使用。',
          code: 'await validatorItem(value, { rule: { required: true }, values, store })',
        },
        {
          name: 'buildEventRulesMapping',
          role: '规则分组',
          description: '按 validateTrigger 将规则分组为事件映射。',
          code: 'const byEvent = buildEventRulesMapping([{ required: true }])',
        },
        {
          name: 'templateConvert',
          role: '消息模板',
          description: '用参数对象替换校验消息模板中的占位符。',
          code: "const message = templateConvert('{label} is required', { label: 'Email' })",
        },
        {
          name: 'namePathToStr',
          role: '路径序列化',
          description: '把 NamePath 转成可用作映射键的字符串。',
          code: "const key = namePathToStr(['profile', 'email'])",
        },
      ],
    },
    {
      title: '表单类型与基础设施',
      navLabel: '类型基础',
      description: '这些导出用于自定义表单容器、类型化字段和表单数据存储。',
      entries: [
        {
          name: 'FormInstance',
          role: '表单契约',
          description: '字段读写、批量值、消息与校验方法的接口。',
          code: 'const form: FormInstance = useForm({})',
          kind: 'type',
        },
        {
          name: 'NamePath',
          role: '字段路径',
          description: 'string、number 或它们组成的路径数组。',
          code: "const name: NamePath = ['profile', 'email']",
          kind: 'type',
        },
        {
          name: 'Rule',
          role: '校验规则',
          description: 'required、长度、pattern、触发事件和自定义 validator 的规则类型。',
          code: "const rule: Rule = { required: true, message: 'Email is required' }",
          kind: 'type',
        },
        {
          name: 'Message',
          role: '校验消息',
          description: '字段 warn 与 error 消息数组。',
          code: "const message: Message = { error: ['Invalid email'] }",
          kind: 'type',
        },
        {
          name: 'FieldData',
          role: '字段数据',
          description: '包含路径和值的兼容字段数据结构。',
          code: "const field: FieldData = { name: ['email'], value: 'ada@example.com' }",
          kind: 'type',
        },
        {
          name: 'FieldInfo',
          role: '字段规则信息',
          description: '字段 label 与 rules 的映射值类型。',
          code: "const info: FieldInfo = { label: 'Email', rules: [{ required: true }] }",
          kind: 'type',
        },
        {
          name: 'FormDataHelpType',
          role: '表单 atom 容器',
          description: '内部 store、values atom 与字段映射 atom 的类型。',
          code: 'const data: FormDataHelpType = createFormDataHelpContext()',
          kind: 'type',
        },
        {
          name: 'CreateDataHelpAtoms',
          role: '容器工厂类型',
          description: 'createFormDataHelpContext 的函数类型。',
          code: 'const createData: CreateDataHelpAtoms = createFormDataHelpContext',
          kind: 'type',
        },
        {
          name: 'createFormDataHelpContext',
          role: '表单 atom 创建',
          description: '创建表单所需 store、values atom、消息与字段规则映射。',
          code: 'const data = createFormDataHelpContext()',
        },
      ],
    },
  ],
}
