import type { ApiPackage } from './types'

export const solidFormApiPackage: ApiPackage = {
  id: 'solid-form',
  label: 'Solid Form',
  packageName: '@einfach/solid-form',
  summary: '基于 atom 的 Solid 表单实例、字段 accessor 与规则校验。',
  sections: [
    {
      title: '表单与字段',
      navLabel: '表单字段',
      description: '表单值是细粒度 atom，字段读取保持 Solid accessor，从而只更新需要的视图。',
      entries: [
        {
          name: 'useForm',
          role: '表单实例',
          description: '创建 FormInstance，可配置 initialValues 与值变更回调。',
          code: "const form = useForm({ initialValues: { email: '' } })",
        },
        {
          name: 'FormProps',
          role: '表单选项',
          description: 'useForm 的 initialValues、onValuesChange 与数据容器工厂属性类型。',
          code: "const props: FormProps<{ email: string }> = { initialValues: { email: '' } }",
          kind: 'type',
        },
        {
          name: 'Form',
          role: '表单 Context',
          description: '通过 Solid Context 向子字段提供 FormInstance。',
          code: '<Form formInstance={form}><ProfileFields /></Form>',
        },
        {
          name: 'FormContext',
          role: '表单 Context',
          description: 'Solid 表单实例 Context。',
          code: 'const form = useContext(FormContext)',
        },
        {
          name: 'useFormContext',
          role: '读取 Context',
          description: '读取当前 Solid FormContext。',
          code: 'const form = useFormContext()',
        },
        {
          name: 'useField',
          role: '字段读写',
          description: '返回 value accessor 和 onChange 写入函数。',
          code: "const field = useField<string>('email', { formInstance: form })\nconsole.log(field.value())",
        },
        {
          name: 'UseFieldOption',
          role: '字段选项',
          description: 'useField 的可选 formInstance。',
          code: 'const options: UseFieldOption = { formInstance: form }',
          kind: 'type',
        },
        {
          name: 'useFieldValue',
          role: '字段订阅',
          description: '订阅指定字段路径并返回 Solid accessor。',
          code: "const email = useFieldValue<string>('email', { formInstance: form })\nconsole.log(email())",
        },
        {
          name: 'UseFieldValueOption',
          role: '读取选项',
          description: 'useFieldValue 的可选 formInstance。',
          code: 'const options: UseFieldValueOption = { formInstance: form }',
          kind: 'type',
        },
        {
          name: 'useSetField',
          role: '字段写入',
          description: '取得写入指定字段路径的函数。',
          code: "const setEmail = useSetField<string>('email', { formInstance: form })\nsetEmail('ada@example.com')",
        },
        {
          name: 'UseSetFieldOption',
          role: '写入选项',
          description: 'useSetField 的可选 formInstance。',
          code: 'const options: UseSetFieldOption = { formInstance: form }',
          kind: 'type',
        },
        {
          name: 'useFormValues',
          role: '表单值订阅',
          description: '订阅完整 values atom 并返回 accessor。',
          code: 'const values = useFormValues(form)\nconsole.log(values())',
        },
        {
          name: 'FormItem',
          role: '字段 UI',
          description: '通过 render function 向子项提供 value 与 onChange，并呈现校验消息。',
          code: '<FormItem name="email" rules={[{ required: true }]}>{({ value, onChange }) => <input value={value} onInput={(event) => onChange(event.currentTarget.value)} />}</FormItem>',
        },
        {
          name: 'FormItemProps',
          role: '字段 UI 属性',
          description: 'FormItem 的 name、rules、formInstance 和 render function 属性。',
          code: "const props: FormItemProps<string> = { name: 'email', children: () => <input /> }",
          kind: 'type',
        },
      ],
    },
    {
      title: '校验',
      navLabel: '校验',
      description: '规则按触发事件组织，字段可以由 UI 事件或表单实例显式验证。',
      entries: [
        {
          name: 'useValidator',
          role: '字段校验',
          description: '注册字段规则，并返回 message accessor 与按事件分组的方法。',
          code: "const { message, methods } = useValidator('email', { rules: [{ required: true }] })\nawait methods.onChange?.()",
        },
        {
          name: 'UseRulesOption',
          role: '校验选项',
          description: 'useValidator 的 formInstance、rules、label 类型。',
          code: 'const options: UseRulesOption = { rules: [{ required: true }] }',
          kind: 'type',
        },
        {
          name: 'validatorItem',
          role: '单条校验',
          description: '按规则校验一个值，供自定义校验流程使用。',
          code: 'await validatorItem(value, { rule: { required: true }, values, store })',
        },
        {
          name: 'buildEventRulesMapping',
          role: '规则分组',
          description: '按 validateTrigger 将规则分组为事件映射。',
          code: 'const byEvent = buildEventRulesMapping([{ required: true }])',
        },
        {
          name: 'templateConvert',
          role: '消息模板',
          description: '用参数对象替换校验消息模板中的占位符。',
          code: "const message = templateConvert('{label} is required', { label: 'Email' })",
        },
        {
          name: 'namePathToStr',
          role: '路径序列化',
          description: '把 NamePath 转成可用作映射键的字符串。',
          code: "const key = namePathToStr(['profile', 'email'])",
        },
      ],
    },
    {
      title: '表单类型与基础设施',
      navLabel: '类型基础',
      description: '这些导出用于自定义容器、类型化字段和表单数据存储。',
      entries: [
        {
          name: 'FormInstance',
          role: '表单契约',
          description: '字段读写、resetValues、消息与校验方法的接口。',
          code: 'const form: FormInstance = useForm({})',
          kind: 'type',
        },
        {
          name: 'NamePath',
          role: '字段路径',
          description: 'string、number 或它们组成的路径数组。',
          code: "const name: NamePath = ['profile', 'email']",
          kind: 'type',
        },
        {
          name: 'Rule',
          role: '校验规则',
          description: 'required、长度、pattern、触发事件和自定义 validator 的规则类型。',
          code: "const rule: Rule = { required: true, message: 'Email is required' }",
          kind: 'type',
        },
        {
          name: 'Message',
          role: '校验消息',
          description: '字段 warn 与 error 消息数组。',
          code: "const message: Message = { error: ['Invalid email'] }",
          kind: 'type',
        },
        {
          name: 'FieldData',
          role: '字段数据',
          description: '包含路径和值的兼容字段数据结构。',
          code: "const field: FieldData = { name: ['email'], value: 'ada@example.com' }",
          kind: 'type',
        },
        {
          name: 'FieldInfo',
          role: '字段规则信息',
          description: '字段 label 与 rules 的映射值类型。',
          code: "const info: FieldInfo = { label: 'Email', rules: [{ required: true }] }",
          kind: 'type',
        },
        {
          name: 'FormDataHelpType',
          role: '表单 atom 容器',
          description: '内部 store、values atom、消息与字段规则映射 atom 的类型。',
          code: 'const data: FormDataHelpType = createFormDataHelpContext()',
          kind: 'type',
        },
        {
          name: 'CreateDataHelpAtoms',
          role: '容器工厂类型',
          description: 'createFormDataHelpContext 的函数类型。',
          code: 'const createData: CreateDataHelpAtoms = createFormDataHelpContext',
          kind: 'type',
        },
        {
          name: 'createFormDataHelpContext',
          role: '表单 atom 创建',
          description: '创建表单所需 store、values atom、消息与字段规则映射。',
          code: 'const data = createFormDataHelpContext()',
        },
      ],
    },
  ],
}
